name: Maven CI
on:
  push

env:
  maven_package_cache: ".m2/repository/"
  MAVEN_OPTS: "-Dmaven.repo.local=./$maven_package_cache"

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Cache Maven Packages
      uses: actions/cache@v2
      with:
        path: $maven_packages_cache
        key: ${{runner.os}}-build
        
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Build with Maven
      working-directory: ueb03
      run: mvn compile
    - name: Use the Upload Artifact GitHub Action
      uses: actions/upload-artifact@v2
      with: 
        name: code-${{ github.job }}-${{ github.sha }}
        path: ueb03/target
        
  test:
    needs: 
      - build
    runs-on: self-hosted
    steps:
    - name: Cache Maven Packages
      uses: actions/cache@v2
      with:
        path: $maven_packages_cache
        key: ${{runner.os}}-build
        
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Test with Maven
      working-directory: ueb03
      run: mvn test
      
  package:
    needs: 
      - test
    runs-on: self-hosted
    steps:
    - name: Cache Maven Packages
      uses: actions/cache@v2
      with:
        path: $maven_packages_cache
        key: ${{runner.os}}-build
        
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Package with Maven
      working-directory: ueb03
      run: mvn package
    - name: Use the Upload Artifact GitHub Action
      uses: actions/upload-artifact@v2
      with: 
        name: war-${{ github.job }}-${{ github.sha }}
        path: ueb03/target/*.war
        
  deploy_test:
      needs:
        - package
      runs-on: self-hosted
      environment:
        name: Test Env
        url: http://localhost:8081/game2048
      steps:
        - name: Deploy War
          working-directory: ueb03
          run: cp -f ./target/*.war /usr/local/tomcat/webapps
